steps:
  - name: maven:3.8.7-openjdk-18
    entrypoint: mvn
    args: ["--version"]
  - name: maven:3.8.7-openjdk-18
    entrypoint: mvn
    args: ["test"]
  - name: maven:3.8.7-openjdk-18
    entrypoint: mvn
    args: ["package","-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "repositorio_name/demo-hello-gke", "--build-arg=JAR_FILE=target/demo-hello-gke-0.0.1-SNAPSHOT.jar", "."]
images: ["repositorio_name/demo-hello-gke"]